/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.view;

import Models.com.Pair;
import Models.com.User;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author cuongnv
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        this.setVisible(true);
        initComponentCustom();
        setLocationRelativeTo(null);
    }
    public void initComponentCustom(){
        jPanelListPlayer.setBackground(new Color(0,0,0,0));
        jPanelGame.setSize(new Dimension(1209, 697));
    }
    class componentBtnPlayer extends JComponent{
        private int status;
        private int width;
        private int height;
        public componentBtnPlayer(int status, int width, int height){
            this.status = status;
            this.width = width;
            this.height = height;
        }
        public void paint(Graphics g){
            //super.paint(g);
            Graphics2D g2d = (Graphics2D) g;
            Color colorStatus = null;
            if(status == 1) colorStatus = Color.GREEN;
            else if(status ==2) colorStatus = Color.orange;
            else colorStatus = Color.red;
            g2d.setColor(colorStatus);
            g2d.fillOval(width-60, 0, 20, 20);
            
            Image img = new ImageIcon(getClass().getResource("/Res/icons8-change-user-30.png")).getImage();
            g2d.drawImage(img,11 ,11 , null);
        }
        protected void paintComponent(Graphics g){
            
        }
    }
    class PanelImage extends JPanel{
        private Image img;
        public PanelImage(String image){
            img = new ImageIcon(getClass().getResource("/Res/"+image)).getImage();
            Dimension size = new Dimension(img.getWidth(this),img.getHeight(this));
            setPreferredSize(size);
            setMinimumSize(size);
            setMaximumSize(size);
            setLayout(null);
        }
        @Override
        protected void paintComponent(Graphics g){
//            Graphics2D g2d = (Graphics2D) g;
//            int width = this.getWidth();
//            int height = this.getHeight();
//            Color cl1 = new Color(0, 143, 233);
//            Color cl2 = new Color(245, 183, 177);
//            GradientPaint gp = new GradientPaint(0, 0, cl1, 100, height, cl2);
//            g2d.setPaint(gp);
//            g2d.fillRect(0, 0, width, height);
            g.drawImage(img,0, 0, null);
        }
    }
    public void showListPlayer(Map<String, Pair<User, Integer>> listPlayer){
        int w = jPanelListPlayer.getWidth(), h = jPanelListPlayer.getHeight();
        Font font  = new Font(Font.SANS_SERIF,Font.BOLD,20);
        for(Map.Entry<String ,Pair<User,Integer>>  player: listPlayer.entrySet()){
            JButton btnPlayer = new JButton(player.getValue().getKey().getUserName()+" ip:"+player.getKey());
            
            btnPlayer.setSize(new Dimension(w,60));
            btnPlayer.add(new componentBtnPlayer(player.getValue().getValue(), w, h));
            
            btnPlayer.setFont(font);
            
            jPanelListPlayer.add(btnPlayer);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGame = new PanelImage("background_game_small.png");
        btnClose = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        jPanelListPlayer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1209, 697));
        setResizable(false);

        jPanelGame.setPreferredSize(new java.awt.Dimension(1209, 697));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/icons8-close.png"))); // NOI18N
        btnClose.setText("    ");
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/icons8-minimize.png"))); // NOI18N
        btnMinimize.setText("    ");
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });
        btnMinimize.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnMinimizeKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListPlayerLayout = new javax.swing.GroupLayout(jPanelListPlayer);
        jPanelListPlayer.setLayout(jPanelListPlayerLayout);
        jPanelListPlayerLayout.setHorizontalGroup(
            jPanelListPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanelListPlayerLayout.setVerticalGroup(
            jPanelListPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelGameLayout = new javax.swing.GroupLayout(jPanelGame);
        jPanelGame.setLayout(jPanelGameLayout);
        jPanelGameLayout.setHorizontalGroup(
            jPanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGameLayout.createSequentialGroup()
                .addGap(0, 1113, Short.MAX_VALUE)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelGameLayout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addComponent(jPanelListPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGameLayout.setVerticalGroup(
            jPanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGameLayout.createSequentialGroup()
                .addGroup(jPanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addComponent(jPanelListPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(380, 380, 380))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnMinimizeKeyPressed
    
    }//GEN-LAST:event_btnMinimizeKeyPressed

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        if(JOptionPane.showConfirmDialog(null,"Bạn chắc chăn muốn thoát game hay này?","Yes",JOptionPane.YES_NO_OPTION)==0){
            this.dispose();
        }
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JPanel jPanelGame;
    private javax.swing.JPanel jPanelListPlayer;
    // End of variables declaration//GEN-END:variables
}
