/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;

/**
 *
 * @author cuongnv
 */
public class Ranking extends javax.swing.JFrame {

    /**
     * Creates new form Ranking
     */
    
    private JPanel[] panelr = new JPanel[5];
    private JLabel[] ranki = new JLabel[5];
    private JLabel[] th = new JLabel[5];
    public Ranking() {
        initComponents();
        customComponent();
        setLocationRelativeTo(null);
    }
    
    public void customComponent() {
        
        this.setBackground(new Color(0, 0, 0, 0));
        panelMain.add(new panelCustom("leaderboard.png"));
        panelMain.setBackground(new Color(0,0,0,0));
        
        initPanel();
        //add(panelScroll);

    }
    
    public void initPanel(){
        Font font = new Font(Font.SANS_SERIF, Font.ITALIC, 20);
        Color fontColor = new Color(254,254,254);
        
        int y = 80;
        for(int i = 0;i<5;i++){
            panelr[i] = new JPanel();
            panelr[i].setSize(410,55);
            panelr[i].setPreferredSize(new Dimension(410,55));
            panelr[i].setLocation(102,y);
            panelr[i].add(new customPanelRank("rankth.png", "1", "cuongnv", "100"));
            panelr[i].setBackground(new Color(0,0,0,0));
          
            

            panelMain.add(panelr[i],3,0);
            
            y+=55;
        }
    }
    class customPanelRank extends  JComponent{
        private int w, h;
        private String s1,s2,s3;
        private Image image;     
        public customPanelRank(String src, String s1, String s2, String s3) {
            image = new ImageIcon(getClass().getResource("/Res/" + src)).getImage();
            w = image.getWidth(this);
            h = image.getHeight(this);
            this.setSize(w, h);
            
            this.setPreferredSize(new Dimension(w, h));
            this.s1= s1;
            this.s2 = s2;
            this.s3 =s3;
        }
        public void paint(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            g2d.drawImage(this.image, 0, 0, null);
            Font font = new Font(Font.SANS_SERIF,Font.ITALIC,20);
            Color fontColor = new Color(254,254,254);
            g2d.setColor(fontColor);
            g2d.setFont(font);
            g2d.drawString(s1, 25 , 40);
            g2d.drawString(s2,150,40);
            g2d.drawString(s3, 300, 40);
        }
    }
    class panelCustom extends JComponent {
        private int w, h;
        private Image image;     
        public panelCustom(String src) {
            image = new ImageIcon(getClass().getResource("/Res/" + src)).getImage();
            w = image.getWidth(this);
            h = image.getHeight(this);
            this.setSize(w, h);
            this.setPreferredSize(new Dimension(w, h));
        }
        public void paint(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            g2d.drawImage(this.image, 0, 0, null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        labelTitle.setFont(new java.awt.Font("Monospaced", 3, 36)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(254, 254, 254));
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("Xếp Hạng");

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelTitle)
                .addContainerGap(352, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ranking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
