/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author cuongnv
 */
public class YouWin extends javax.swing.JFrame {
    private int width;
    private int height;
    private JPanel panelWin;
    /**
     * Creates new form YouWin
     */
    public YouWin() {
        initComponents();
        this.setBackground(new Color(111,111,111,0));
        width = getWidth();
        height = getHeight();
        panelWin = new JPanel();
        Font font  = new Font(Font.SANS_SERIF,Font.BOLD, 28);
        Color fontColor = new Color(254,254,254);
        panelWin.setSize(451 ,450);
        panelWin.setPreferredSize(new Dimension(451,450));
        panelWin.add(new customPanel("youwin.png"));
        panelWin.setBackground(new Color(20,111,112,0));
        panelWin.setLayout(null);
        panelMain.add(panelWin);
        panelMain.setBackground(new Color(0,0,0,0));
        panelBtnRematch.setBackground(new Color(0,0,0,0));
        panelBtnExit.setBackground(new Color(0,0,0,0));
        btnExit.setForeground(fontColor);
        btnReMatch.setForeground(fontColor);
        btnExit.setFont(font);
        btnReMatch.setFont(font);
        btnExit.setHorizontalAlignment(JLabel.CENTER);
        btnReMatch.setHorizontalAlignment(JLabel.CENTER);
        
        btnExit.setName("btnEitResult");
        btnReMatch.setName("btnReMatch");
        btnExit.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnReMatch.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        btnExit.setText("Thoát");
        btnReMatch.setText("Đấu lại");
        panelBtnRematch.add(new customPanel("btn_rematch.png"));
        panelBtnExit.add(new customPanel("btn_rematch.png"));
        //this.setBackground(Color.RED);
        setLocationRelativeTo(null);
        
        
    }
    public void setDetail(String s){
        this.labelDetail.setText(s);
    }
    public void addListenBtnExitAndRematch(MouseListener m){
        btnExit.addMouseListener(m);
        btnReMatch.addMouseListener(m);
    }
    class customPanel extends JComponent{
        private int w;
        private int h;
        private Image image;
        public customPanel(String img){
            image = new ImageIcon(getClass().getResource("/Res/"+img)).getImage();
            w = image.getWidth(this);
            h = image.getHeight(this);
            this.setSize(w,h);
            this.setPreferredSize(new Dimension(w,h));
        }
        public void paint(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
            g2d.drawImage(this.image,0, 0, this);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        labelDetail = new javax.swing.JLabel();
        panelBtnRematch = new javax.swing.JPanel();
        btnReMatch = new javax.swing.JLabel();
        panelBtnExit = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelMain.setForeground(new java.awt.Color(255, 0, 0));

        labelDetail.setFont(new java.awt.Font("Sarai", 1, 36)); // NOI18N
        labelDetail.setForeground(new java.awt.Color(254, 0, 62));
        labelDetail.setText("10/10      15s");

        panelBtnRematch.setPreferredSize(new java.awt.Dimension(200, 77));

        javax.swing.GroupLayout panelBtnRematchLayout = new javax.swing.GroupLayout(panelBtnRematch);
        panelBtnRematch.setLayout(panelBtnRematchLayout);
        panelBtnRematchLayout.setHorizontalGroup(
            panelBtnRematchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnReMatch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        panelBtnRematchLayout.setVerticalGroup(
            panelBtnRematchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnRematchLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(btnReMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelBtnExit.setPreferredSize(new java.awt.Dimension(200, 77));

        javax.swing.GroupLayout panelBtnExitLayout = new javax.swing.GroupLayout(panelBtnExit);
        panelBtnExit.setLayout(panelBtnExitLayout);
        panelBtnExitLayout.setHorizontalGroup(
            panelBtnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        panelBtnExitLayout.setVerticalGroup(
            panelBtnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnExitLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBtnRematch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(panelBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(labelDetail)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap(386, Short.MAX_VALUE)
                .addComponent(labelDetail)
                .addGap(18, 18, 18)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBtnRematch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YouWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YouWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YouWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YouWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YouWin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnReMatch;
    private javax.swing.JLabel labelDetail;
    private javax.swing.JPanel panelBtnExit;
    private javax.swing.JPanel panelBtnRematch;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
